name: CD Deploy

on:
  push:
    branches: [main]

<<<<<<< HEAD
=======
# Necessary for Workload Identity Federation
>>>>>>> 03099f43c92368c072bbb987504ab54efb3bf4d1
permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'influential-sky-488915-u9'
          workload_identity_provider: 'projects/282679082866/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@influential-sky-488915-u9.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init -backend-config="bucket=${{ secrets.GCP_PROJECT_ID }}-tfstate"

      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

  deploy-telemetry-api:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'influential-sky-488915-u9'
          workload_identity_provider: 'projects/282679082866/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@influential-sky-488915-u9.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Build and Push to Artifact Registry
        working-directory: services/telemetry-ingestion-api
        run: |
          gcloud builds submit --tag asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/omnistream-repo/ingestion-api:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy telemetry-ingestion-api \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/omnistream-repo/ingestion-api:${{ github.sha }} \
            --region asia-south1 \
            --platform managed

  deploy-analytics-processor:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'influential-sky-488915-u9'
          workload_identity_provider: 'projects/282679082866/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@influential-sky-488915-u9.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy Cloud Function
        working-directory: services/analytics-processor
        run: |
          gcloud functions deploy analytics-processor-dev \
            --runtime python311 \
            --trigger-topic telemetry-events \
            --region asia-south1 \
            --entry-point process_telemetry \
            --service-account "analytics-processor-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com" \
            --set-env-vars PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}